
quarkus.http.port=8123


mp.jwt.verify.publickey.location=keys/publicKey.pem
mp.jwt.verify.issuer=quarkus-app

quarkus.native.resources.includes=keys/privateKey.pem,keys/publicKey.pem



# Users: username=password,role
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.admin=admin123
quarkus.security.users.embedded.roles.admin=admin
quarkus.security.users.embedded.users.user=user123
quarkus.security.users.embedded.roles.user=user


quarkus.redis.hosts=redis://localhost:6379